# Generated by Django 6.0 on 2025-12-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
