# Generated by Django 5.2.8 on 2025-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='If true, applies every day (for lunch breaks)'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
