# Generated by Django 6.0 on 2025-12-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_doctoravailability_availability_type_and_more'),
        ('hospital', '0003_appointment_reminder_sent'),
    ]

    operations = [
    ]
