# Generated by Django 6.0 on 2025-12-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_merge_20251219_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('PATIENT', 'Patient'), ('ADMIN', 'Admin'), ('SUPERUSER', 'Superuser')], default='PATIENT', max_length=20),
        ),
    ]
